# Project information
site_name: AGAT
site_author: Jacques Dainat
site_url: 'https://github.com/NBISweden/AGAT'
site_description: AGAT
site_dir: public # When you build your site, all of the files are written to the directory assigned to the site_dir configuration option (defaults to "site")
docs_dir: docs # The directory that holds the documentation source files (the MkDocs documentation)

# Repository
repo_name: 'AGAT'
repo_url: 'https://github.com/NBISweden/AGAT'
edit_uri: edit/main/docs/ # Allow to replace edit/master/docs use by default

# Configuration
theme:
  name: material
  logo: img/NBIS.png # logo top left page
  search_index_only: true
  include_search_page: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections # collapse subsections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate # remove table of content on the right side
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets:
     base_path: docs
  - attr_list
  - tables
  - toc:
      permalink: '#'

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - macros

# Customization
extra:
#  homepage:  # Page displayed when clicking the logo
  history_buttons: false
  # --- set whole scope variables ---
  contact: jacques.dainat@gmail.com
  institute: NBIS
  unit: NBIS
  color_table_header: "#333a99"

# page tree
nav:
    - AGAT Home: 
      - index.md
      - agat_for_you.md
      - agat_how_does_it_work.md
      - how_to_cite.md
      - why_agat.md
    - The GTF/GFF formats:
      - gxf.md
    - AGAT vs other tools:
      - topological-sorting-of-gff-features.md
      - gff_to_bed.md
      - gff_to_gtf.md
    - AGAT Tools:
      - tools/agat_convert_bed2gff.md
      - tools/agat_convert_embl2gff.md
      - tools/agat_convert_genscan2gff.md
      - tools/agat_convert_mfannot2gff.md
      - tools/agat_convert_minimap2_bam2gff.md
      - tools/agat_convert_sp_gff2bed.md
      - tools/agat_convert_sp_gff2gtf.md
      - tools/agat_convert_sp_gff2tsv.md
      - tools/agat_convert_sp_gff2zff.md
      - tools/agat_convert_sp_gxf2gxf.md
      - tools/agat_sp_Prokka_inferNameFromAttributes.md
      - tools/agat_sp_add_intergenic_regions.md
      - tools/agat_sp_add_introns.md
      - tools/agat_sp_add_splice_sites.md
      - tools/agat_sp_add_start_and_stop.md
      - tools/agat_sp_alignment_output_style.md
      - tools/agat_sp_clipN_seqExtremities_and_fixCoordinates.md
      - tools/agat_sp_compare_two_BUSCOs.md
      - tools/agat_sp_compare_two_annotations.md
      - tools/agat_sp_complement_annotations.md
      - tools/agat_sp_ensembl_output_style.md
      - tools/agat_sp_extract_attributes.md
      - tools/agat_sp_extract_sequences.md
      - tools/agat_sp_filter_by_ORF_size.md
      - tools/agat_sp_filter_by_locus_distance.md
      - tools/agat_sp_filter_by_mrnaBlastValue.md
      - tools/agat_sp_filter_feature_by_attribute_presence.md
      - tools/agat_sp_filter_feature_by_attribute_value.md
      - tools/agat_sp_filter_feature_from_keep_list.md
      - tools/agat_sp_filter_feature_from_kill_list.md
      - tools/agat_sp_filter_gene_by_intron_numbers.md
      - tools/agat_sp_filter_gene_by_length.md
      - tools/agat_sp_filter_incomplete_gene_coding_models.md
      - tools/agat_sp_filter_record_by_coordinates.md
      - tools/agat_sp_fix_cds_phases.md
      - tools/agat_sp_fix_features_locations_duplicated.md
      - tools/agat_sp_fix_fusion.md
      - tools/agat_sp_fix_longest_ORF.md
      - tools/agat_sp_fix_overlaping_genes.md
      - tools/agat_sp_fix_small_exon_from_extremities.md
      - tools/agat_sp_flag_premature_stop_codons.md
      - tools/agat_sp_flag_short_introns.md
      - tools/agat_sp_functional_statistics.md
      - tools/agat_sp_gxf_to_gff3.md
      - tools/agat_sp_keep_longest_isoform.md
      - tools/agat_sp_kraken_assess_liftover.md
      - tools/agat_sp_list_short_introns.md
      - tools/agat_sp_load_function_from_protein_align.md
      - tools/agat_sp_manage_IDs.md
      - tools/agat_sp_manage_UTRs.md
      - tools/agat_sp_manage_attributes.md
      - tools/agat_sp_manage_functional_annotation.md
      - tools/agat_sp_manage_introns.md
      - tools/agat_sp_merge_annotations.md
      - tools/agat_sp_move_attributes_within_records
      - tools/agat_sp_prokka_fix_fragmented_gene_annotations.md
      - tools/agat_sp_sensitivity_specificity.md
      - tools/agat_sp_separate_by_record_type.md
      - tools/agat_sp_split_by_level2_feature.md
      - tools/agat_sp_statistics.md
      - tools/agat_sp_to_tabulated.md
      - tools/agat_sp_webApollo_compliant.md
      - tools/agat_sq_add_attributes_from_tsv.md
      - tools/agat_sq_add_hash_tag.md
      - tools/agat_sq_add_locus_tag.md
      - tools/agat_sq_filter_feature_from_fasta.md
      - tools/agat_sq_list_attributes.md
      - tools/agat_sq_manage_IDs.md
      - tools/agat_sq_manage_attributes.md
      - tools/agat_sq_mask.md
      - tools/agat_sq_remove_redundant_entries.md
      - tools/agat_sq_repeats_analyzer.md
      - tools/agat_sq_reverse_complement.md
      - tools/agat_sq_rfam_analyzer.md
      - tools/agat_sq_split.md
      - tools/agat_sq_stat_basic.md
    - Troubleshooting: 
      - troubleshooting.md