name: documentation
on:
  push:
    paths:
      - 'docs/**'
      - mkdocs.yml
  pull_request:
    branches: [main, master]
    paths:
      - 'docs/**'
      - mkdocs.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
permissions:
  contents: write
jobs:
  deploy:
    # avoid to run twice push and PR
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pymdown-extensions
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-macros-plugin
      - run: pip install mkdocs-embed-external-markdown
      - run: pip install mkdocs-table-reader-plugin
      - run: mkdocs gh-deploy --force
